version: '3.8'

services:
  postgres:
    container_name: ms_register_postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ms_register
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - localstack_network

volumes:
  localstack_data:
  pgdata:

networks:
  localstack_network:
    driver: bridge
